name: model-training

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          
          python data_extraction.py

          python train.py
        
          cat cml_objects/metrics.txt >> report.md
          
          cml-publish cml_objects/confusion_matrix.png --md >> report.md
          
          cml-send-comment report.md

          python data_cleaup.py