name: model-training

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd

          ls -la

          pip install -r requirements.txt

          pytest cml_layman_brothers/src/test/unit_test/test_requirements.py -o log_cli=true --log-cli-level=INFO

          pytest cml_layman_brothers/src/test/unit_test/test_data_extraction.py -o log_cli=true --log-cli-level=INFO

          pip install numpy==1.22.0

          python3 cml_layman_brothers/src/main/processing/data_extraction.py

          python3 cml_layman_brothers/src/main/processing/train.py

          cat metrics.txt >> report.md

          cml-publish confusion_matrix.png --md >> report.md

          cml-send-comment report.md

          python cml_layman_brothers/src/main/processing/data_cleanup.py
